spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ulkar.mustafazada@gmail.com
    password: jqsg efaq bhhi elie
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: taskstudent
  datasource:
    url: jdbc:postgresql://localhost:5433/mydatabase
    username: myuser
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
  servlet:
    session:
      persistent: false
jwt:
  expire: 2592000000
  secret: 1234567898327651751834402182910384756473829387483292789949112

